event_page/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the subscribe application 
from django.urls import include

urlpatterns += [
    path('subscribe/', include('subscribe.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/subscribe/')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

subscribe/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('subscribers/', views.SubscriberListView.as_view(), name='subscribers'),
    path('subscriber/<int:pk>', views.SubscriberDetailView.as_view(), name='subscriber-detail'),
    path('subscriber/create/', views.SubscriberCreate.as_view(), name='subscriber_create'),
]

subscribe/____old___/models.py
from django.db import models

# Create your models here.

subscribe/models.py
from django.db import models

        
from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Subscriber(models.Model):
    """
    Model representing a subscriber.
    """
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
        
    def get_absolute_url(self):
        """
        Returns the url to access a particular subscriber instance.
        """
        return reverse('subscriber-detail', args=[str(self.id)])
    

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '{0} ({1})'.format(self.name,self.email)


        

subscribe/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.
    
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        #Check date is not in past. 
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        #Check date is in range librarian allowed to change (+4 weeks).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

subscribe/____old___/views.py
from django.shortcuts import render

# Create your views here.

subscribe/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView
# Create your views here.
from .models import Subscriber

def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_subscriber = Subscriber.objects.all().count()
    
    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_subscriber':num_subscriber},
    )
    
class SubscriberListView(generic.ListView):
    model = Subscriber
    
class SubscriberDetailView(generic.DetailView):
    model = Subscriber
    
class SubscriberCreate(CreateView):
    model = Subscriber
    fields = '__all__'

    

subscribe/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title> My Event</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'subscribers' %}">All Subscribers</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      <br />
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

subscribe/templates/index.html
{% extends "base_generic.html" %}
{% block title %}
<title> My Event </title>
{% endblock %}

{% block content %}
<h1>Event Home</h1>

  <p>Welcome to <em>My Event</em>!</p>
  <p>We have {{ num_subscriber }} subscribers to date.</p>
  <p>
  Click <a href="{% url 'subscriber_create' %}">here</a> to subscribe. 
  
  <p>
{% endblock %}

subscribe/templates/subscribe/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

subscribe/templates/subscribe/author_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

subscribe/templates/subscribe/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

subscribe/templates/subscribe/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Subscriber List</h1>

    {% if subscriber_list %}
    <ul>

      {% for subscriber in subscriber_list %}
      <li>
        <a href="{{ subscriber.get_absolute_url }}">{{ subscriber.name }}</a> ({{subscriber.email}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no subscriber for the event.</p>
    {% endif %}       
{% endblock %}

subscribe/templates/subscribe/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

subscribe/templates/subscribe/subscriber_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <p><br />Subscriber added!<br /><p>
  <h1>Name: {{ subscriber.name }}</h1>
  <p><strong>Email:</strong> {{ subscriber.email }}</p>
  <p><br />Return to <a href="{% url 'index' %}">Home</a></p>
  
{% endblock %}

subscribe/templates/subscribe/subscriber_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

subscribe/templates/subscribe/subscriber_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Subscriber List</h1>

    {% if subscriber_list %}
    <ol>

      {% for subscriber in subscriber_list %}
      <li>
        {{ subscriber.name }} (<a href="mailto:{{ subscriber.email }}">{{subscriber.email}}</a>)
      </li>
      {% endfor %}

    </ol>
    {% else %}
      <p>There are no subscriber for the event.</p>
    {% endif %}       
{% endblock %}